# SPDX-FileCopyrightText: 2025 Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

---
fetch: "False"
force: "False"
# path where datasets will be downloaded to and stored
download_dir: "datasets"
